/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author ahsen
 */
public class AnaMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AnaMenu.class.getName());

    /**
     * Creates new form AnaMenu
     */
    public AnaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOgrenciKayit = new javax.swing.JButton();
        btnOduncVer = new javax.swing.JButton();
        btnCikisYap = new javax.swing.JButton();
        btnKitapEkle = new javax.swing.JButton();
        btnIadeAl = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnOgrenciKayit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnOgrenciKayit.setForeground(new java.awt.Color(204, 0, 0));
        btnOgrenciKayit.setText("Öğrenci Kayıt");
        btnOgrenciKayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOgrenciKayitActionPerformed(evt);
            }
        });

        btnOduncVer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnOduncVer.setForeground(new java.awt.Color(204, 0, 0));
        btnOduncVer.setText("Kitap Ödünç Ver");
        btnOduncVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOduncVerActionPerformed(evt);
            }
        });

        btnCikisYap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCikisYap.setForeground(new java.awt.Color(204, 0, 0));
        btnCikisYap.setText("Çıkış Yap");
        btnCikisYap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCikisYapActionPerformed(evt);
            }
        });

        btnKitapEkle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKitapEkle.setForeground(new java.awt.Color(204, 0, 0));
        btnKitapEkle.setText("Kitap Ekle");
        btnKitapEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitapEkleActionPerformed(evt);
            }
        });

        btnIadeAl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIadeAl.setForeground(new java.awt.Color(204, 0, 0));
        btnIadeAl.setText("Kitap İade Al");
        btnIadeAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIadeAlActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ANA MENÜ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnOduncVer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOgrenciKayit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnIadeAl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnKitapEkle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(82, 82, 82))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnCikisYap)
                                .addGap(31, 31, 31))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKitapEkle)
                    .addComponent(btnOgrenciKayit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIadeAl)
                    .addComponent(btnOduncVer))
                .addGap(39, 39, 39)
                .addComponent(btnCikisYap)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOgrenciKayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOgrenciKayitActionPerformed
       OgrenciKayitFormu ogrenciFormu = new OgrenciKayitFormu();
       ogrenciFormu.setVisible(true);
    }//GEN-LAST:event_btnOgrenciKayitActionPerformed

    private void btnKitapEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitapEkleActionPerformed
        KitapEkleFormu kitapFormu = new KitapEkleFormu();
        kitapFormu.setVisible(true);
    }//GEN-LAST:event_btnKitapEkleActionPerformed

    private void btnCikisYapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCikisYapActionPerformed
        //ana menüyü kapat
        this.dispose();
        
        // Giriş Ekranını tekrar aç
        GirisEkrani giris = new GirisEkrani();
        giris.setVisible(true);
    }//GEN-LAST:event_btnCikisYapActionPerformed

    private void btnOduncVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOduncVerActionPerformed
        OduncVerFormu oduncFormu = new OduncVerFormu();
        oduncFormu.setVisible(true);
    }//GEN-LAST:event_btnOduncVerActionPerformed

    private void btnIadeAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIadeAlActionPerformed
        KitapIadeFormu iadeFormu = new KitapIadeFormu();
        iadeFormu.setVisible(true);
    }//GEN-LAST:event_btnIadeAlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AnaMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCikisYap;
    private javax.swing.JButton btnIadeAl;
    private javax.swing.JButton btnKitapEkle;
    private javax.swing.JButton btnOduncVer;
    private javax.swing.JButton btnOgrenciKayit;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
