/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import veritabani.Baglanti;

public class KitapIadeFormu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KitapIadeFormu.class.getName());

    /**
     * Creates new form KitapIadeFormu
     */
    public KitapIadeFormu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtKitapID = new javax.swing.JTextField();
        txtOduncAlanOgrenci = new javax.swing.JTextField();
        txtKitapAdi = new javax.swing.JTextField();
        btnKitapAra = new javax.swing.JButton();
        btnIadeAl = new javax.swing.JButton();

        jTextField3.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KİTAP İADE AL");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Kitap ID: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Kitap Adı: ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Ödünç Alan Öğrenci:");

        txtOduncAlanOgrenci.setEditable(false);

        txtKitapAdi.setEditable(false);

        btnKitapAra.setBackground(new java.awt.Color(204, 0, 0));
        btnKitapAra.setForeground(new java.awt.Color(255, 255, 255));
        btnKitapAra.setText("Kitap Ara");
        btnKitapAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitapAraActionPerformed(evt);
            }
        });

        btnIadeAl.setBackground(new java.awt.Color(204, 0, 0));
        btnIadeAl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIadeAl.setForeground(new java.awt.Color(255, 255, 255));
        btnIadeAl.setText("İADE AL");
        btnIadeAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIadeAlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnKitapAra)
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(89, 89, 89)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtKitapAdi, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                    .addComponent(txtKitapID)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtOduncAlanOgrenci, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(btnIadeAl, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKitapID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(btnKitapAra)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKitapAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtOduncAlanOgrenci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnIadeAl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKitapAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitapAraActionPerformed
        String kitapID_str = txtKitapID.getText().trim();

        if (kitapID_str.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lütfen bir Kitap ID girin!", "Uyarı", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int kitapID;
        try {
            kitapID = Integer.parseInt(kitapID_str);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Kitap ID bir sayı olmalıdır!", "Hata", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Connection conn = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        // SQL: Kitap adını ve ödünç alan öğrenci ID'sini al, sadece "Ödünç Verildi" durumundaysa
        String sql = "SELECT k.kitap_adi, o.isim AS ogrenci_adi " +
                     "FROM kitaplar k " +
                     "LEFT JOIN ogrenciler o ON k.odunc_alan_ogrenci_id = o.ogrenci_id " +
                     "WHERE k.kitap_id = ? AND k.durum = 'Ödünç Verildi'";

        try {
            conn = Baglanti.baglan();
            if (conn == null) {
                JOptionPane.showMessageDialog(this, "Veritabanı bağlantısı kurulamadı!", "Hata", JOptionPane.ERROR_MESSAGE);
                return;
            }

            ps = conn.prepareStatement(sql);
            ps.setInt(1, kitapID);
            rs = ps.executeQuery();

            if (rs.next()) {
                String kitapAdi = rs.getString("kitap_adi");
                String ogrenciAdi = rs.getString("ogrenci_adi"); // Öğrenci adı zaten var mıydı kontrol et
                
                txtKitapAdi.setText(kitapAdi);
                txtOduncAlanOgrenci.setText(ogrenciAdi != null ? ogrenciAdi : "Bilinmiyor"); // Öğrenci yoksa "Bilinmiyor" yaz

            } else {
                // Kitap bulunamadı veya ödünç verilmemiş
                JOptionPane.showMessageDialog(this, "Belirtilen Kitap ID'ye sahip, ödünç verilmiş bir kitap bulunamadı!", "Kitap Bulunamadı", JOptionPane.ERROR_MESSAGE);
                txtKitapID.setText("");
                txtKitapAdi.setText("");
                txtOduncAlanOgrenci.setText("");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Veritabanı hatası: " + e.getMessage(), "Hata", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (rs != null) rs.close();
                if (ps != null) ps.close();
                if (conn != null) conn.close();
            } catch (SQLException e) {
                System.err.println("Kaynakları kapatırken hata: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnKitapAraActionPerformed

    private void btnIadeAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIadeAlActionPerformed
        // 1. Gerekli bilgileri al
        String kitapID_str = txtKitapID.getText();
        String kitapAdi = txtKitapAdi.getText();

        // 2. Kontrol: "Kitap Ara" butonu kullanılmış mı?
        //    (Eğer kitap adı kutusu boşsa, 'Ara'ya basılmamış demektir)
        if (kitapAdi.isEmpty() || kitapID_str.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lütfen önce iade edilecek kitabı 'Kitap Ara' butonuyla bulun!", "Eksik Bilgi", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 3. Veritabanı UPDATE işlemi
        Connection conn = null;
        PreparedStatement ps = null;
        // SQL: Kitabın durumunu 'Rafta' yap, tarihleri ve öğrenci ID'sini NULL (boş) yap.
        String sql = "UPDATE kitaplar SET " +
                     "durum = 'Rafta', " +
                     "odunc_tarihi = NULL, " +
                     "iade_tarihi = NULL, " +
                     "odunc_alan_ogrenci_id = NULL " +
                     "WHERE kitap_id = ? AND durum = 'Ödünç Verildi'";

        try {
            conn = Baglanti.baglan();
            if (conn == null) {
                JOptionPane.showMessageDialog(this, "Veritabanı bağlantısı kurulamadı!", "Hata", JOptionPane.ERROR_MESSAGE);
                return;
            }

            ps = conn.prepareStatement(sql);
            ps.setInt(1, Integer.parseInt(kitapID_str)); // WHERE şartı için Kitap ID'si

            // 4. Sorguyu çalıştır
            int sonuc = ps.executeUpdate();

            if (sonuc > 0) {
                JOptionPane.showMessageDialog(this, "'" + kitapAdi + "' adlı kitap başarıyla iade alındı!");

                // Formu temizle
                txtKitapID.setText("");
                txtKitapAdi.setText("");
                txtOduncAlanOgrenci.setText("");
                
            } else {
                // Bu durum, 'Ara'ya bastıktan sonra bir sorun oluşursa 
                // veya kitap 'Ödünç Verildi' durumunda değilse oluşur.
                JOptionPane.showMessageDialog(this, "İade işlemi başarısız oldu. Kitabın durumunu kontrol edin.", "İşlem Başarısız", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Veritabanı hatası: " + e.getMessage(), "Hata", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Kitap ID formatı geçersiz!", "Format Hatası", JOptionPane.ERROR_MESSAGE);
        } finally {
            // 5. Bağlantıları her zaman kapat!
            try {
                if (ps != null) ps.close();
                if (conn != null) conn.close();
            } catch (SQLException e) {
                System.err.println("Kaynakları kapatırken hata: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnIadeAlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KitapIadeFormu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIadeAl;
    private javax.swing.JButton btnKitapAra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField txtKitapAdi;
    private javax.swing.JTextField txtKitapID;
    private javax.swing.JTextField txtOduncAlanOgrenci;
    // End of variables declaration//GEN-END:variables
}
