/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import veritabani.Baglanti;


public class KitapEkleFormu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KitapEkleFormu.class.getName());

    /**
     * Creates new form KitapEkleFormu
     */
    public KitapEkleFormu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKitapID = new javax.swing.JTextField();
        txtKitapAdi = new javax.swing.JTextField();
        txtYayinevi = new javax.swing.JTextField();
        txtFiyat = new javax.swing.JTextField();
        txtYayinYili = new javax.swing.JTextField();
        btnKitapKaydet = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Kitap ID:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Kitap Adı:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Yayınevi:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Fiyat:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Yayın Yılı:");

        txtKitapID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKitapIDActionPerformed(evt);
            }
        });

        btnKitapKaydet.setBackground(new java.awt.Color(204, 0, 0));
        btnKitapKaydet.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKitapKaydet.setForeground(new java.awt.Color(255, 255, 255));
        btnKitapKaydet.setText("KAYDET");
        btnKitapKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitapKaydetActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("KİTAP EKLEME");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtKitapID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKitapAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYayinevi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYayinYili, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81))
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(btnKitapKaydet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(39, 39, 39)
                        .addComponent(btnKitapKaydet))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtKitapID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtKitapAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtYayinevi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtFiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtYayinYili, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKitapKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitapKaydetActionPerformed
        // 1. Metin kutularından verileri al (Sayısal alanlar için .trim() çok önemli!)
        String kitapID_str = txtKitapID.getText().trim();
        String kitapAdi = txtKitapAdi.getText();
        String yayinevi = txtYayinevi.getText();
        String fiyat_str = txtFiyat.getText().trim();
        String yayinYili_str = txtYayinYili.getText().trim();

        // 2. Boş alan kontrolü
        if (kitapID_str.isEmpty() || kitapAdi.isEmpty() || yayinevi.isEmpty() || fiyat_str.isEmpty() || yayinYili_str.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tüm alanlar doldurulmalıdır!", "Hata", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int kitapID, yayinYili;
        double fiyat;

        // 3. Sayısal dönüşümleri yap
        try {
            kitapID = Integer.parseInt(kitapID_str);
            fiyat = Double.parseDouble(fiyat_str);       // Fiyat için Double
            yayinYili = Integer.parseInt(yayinYili_str); // Yıl için Integer
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Kitap ID, Fiyat ve Yayın Yılı sayısal olmalıdır!", "Format Hatası", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 4. Veritabanı işlemleri
        Connection conn = null;
        PreparedStatement ps = null;
        // Yeni eklenen kitabın durumunu varsayılan olarak "Rafta" yapıyoruz.
        String sql = "INSERT INTO kitaplar (kitap_id, kitap_adi, yayinevi, fiyat, yayin_yili, durum) VALUES (?, ?, ?, ?, ?, ?)";

        try {
            conn = Baglanti.baglan();
            if (conn == null) {
                JOptionPane.showMessageDialog(this, "Veritabanı bağlantı hatası!", "Hata", JOptionPane.ERROR_MESSAGE);
                return;
            }

            ps = conn.prepareStatement(sql);
            ps.setInt(1, kitapID);
            ps.setString(2, kitapAdi);
            ps.setString(3, yayinevi);
            ps.setDouble(4, fiyat);
            ps.setInt(5, yayinYili);
            ps.setString(6, "Rafta"); // 6. soru işareti: Varsayılan durum

            // 5. Sorguyu çalıştır
            int sonuc = ps.executeUpdate();

            if (sonuc > 0) {
                JOptionPane.showMessageDialog(this, "Kitap başarıyla kaydedildi!");
                
                // Kutuları temizle
                txtKitapID.setText("");
                txtKitapAdi.setText("");
                txtYayinevi.setText("");
                txtFiyat.setText("");
                txtYayinYili.setText("");
            }

        } catch (SQLException e) {
            // "Duplicate entry" hatası (Primary Key ihlali)
            if (e.getErrorCode() == 1062) {
                JOptionPane.showMessageDialog(this, "Bu Kitap ID zaten kayıtlı!", "Kayıt Hatası", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Veritabanı hatası: " + e.getMessage(), "Hata", JOptionPane.ERROR_MESSAGE);
            }
        } finally {
            // 6. Bağlantıları her zaman kapat!
            try {
                if (ps != null) ps.close();
                if (conn != null) conn.close();
            } catch (SQLException e) {
                System.err.println("Kaynakları kapatırken hata: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnKitapKaydetActionPerformed

    private void txtKitapIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKitapIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKitapIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KitapEkleFormu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKitapKaydet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtFiyat;
    private javax.swing.JTextField txtKitapAdi;
    private javax.swing.JTextField txtKitapID;
    private javax.swing.JTextField txtYayinYili;
    private javax.swing.JTextField txtYayinevi;
    // End of variables declaration//GEN-END:variables
}
