/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat; // Tarih formatlamak için
import java.util.Date;             // Bugünün tarihini almak için
import javax.swing.JOptionPane;
import veritabani.Baglanti;

public class OduncVerFormu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OduncVerFormu.class.getName());

    /**
     * Creates new form OduncVerFormu
     */
    public OduncVerFormu() {
        initComponents();
        // Form açıldığında ödünç tarihini otomatik olarak bugünün tarihiyle doldur
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        txtOduncTarihi.setText(sdf.format(new Date()));
        txtOduncTarihi.setEditable(false); // Kullanıcının değiştirmesini engelle
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtOgrenciID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtOgrenciAdi = new javax.swing.JTextField();
        btnOgrenciAra = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtKitapID = new javax.swing.JTextField();
        btnKitapAra = new javax.swing.JButton();
        txtKitapAdi = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtOduncTarihi = new javax.swing.JTextField();
        txtIadeTarihi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnOduncVer = new javax.swing.JButton();

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Öğrenci Bilgileri");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Öğrenci ID: ");

        txtOgrenciID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOgrenciIDActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Öğrenci Adı: ");

        txtOgrenciAdi.setEditable(false);
        txtOgrenciAdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOgrenciAdiActionPerformed(evt);
            }
        });

        btnOgrenciAra.setBackground(new java.awt.Color(204, 0, 0));
        btnOgrenciAra.setForeground(new java.awt.Color(255, 255, 255));
        btnOgrenciAra.setText("Öğrenci Ara");
        btnOgrenciAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOgrenciAraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOgrenciID, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOgrenciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnOgrenciAra)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtOgrenciID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtOgrenciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOgrenciAra)
                        .addGap(40, 40, 40))))
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Kitap Bilgileri");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Kitap ID: ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Kitap Adı: ");

        txtKitapID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKitapIDActionPerformed(evt);
            }
        });

        btnKitapAra.setBackground(new java.awt.Color(204, 0, 0));
        btnKitapAra.setForeground(new java.awt.Color(255, 255, 255));
        btnKitapAra.setText("Kitap Ara");
        btnKitapAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitapAraActionPerformed(evt);
            }
        });

        txtKitapAdi.setEditable(false);
        txtKitapAdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKitapAdiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKitapID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKitapAdi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnKitapAra)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtKitapID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtKitapAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnKitapAra)
                                .addGap(18, 18, 18)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Tarih Bilgileri");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Ödünç Alınan Tarih: ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("İade Tarihi (YYYY-AA-GG):");

        txtOduncTarihi.setEditable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOduncTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIadeTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtOduncTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtIadeTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("KİTAP ÖDÜNÇ VERME");

        btnOduncVer.setBackground(new java.awt.Color(204, 0, 0));
        btnOduncVer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnOduncVer.setForeground(new java.awt.Color(255, 255, 255));
        btnOduncVer.setText("ÖDÜNÇ VER");
        btnOduncVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOduncVerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(btnOduncVer, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOduncVer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKitapIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKitapIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKitapIDActionPerformed

    private void btnKitapAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitapAraActionPerformed
     String kitapID_str = txtKitapID.getText().trim();

        if (kitapID_str.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lütfen bir Kitap ID girin!", "Uyarı", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int kitapID;
        try {
            kitapID = Integer.parseInt(kitapID_str);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Kitap ID bir sayı olmalıdır!", "Hata", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Connection conn = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String sql = "SELECT kitap_adi, durum FROM kitaplar WHERE kitap_id = ?";

        try {
            conn = Baglanti.baglan();
            if (conn == null) {
                JOptionPane.showMessageDialog(this, "Veritabanı bağlantısı kurulamadı!", "Hata", JOptionPane.ERROR_MESSAGE);
                return;
            }

            ps = conn.prepareStatement(sql);
            ps.setInt(1, kitapID);
            rs = ps.executeQuery();

            if (rs.next()) {
                String kitapAdi = rs.getString("kitap_adi");
                String durum = rs.getString("durum");
                txtKitapAdi.setText(kitapAdi); // Kitap adını kutuya yaz

                if ("Rafta".equalsIgnoreCase(durum)) { // Durumu kontrol et
                    // Kitap raftaysa sorun yok
                } else {
                    JOptionPane.showMessageDialog(this, "Bu kitap şu an " + durum + " durumunda ve ödünç verilemez!", "Kitap Durumu", JOptionPane.WARNING_MESSAGE);
                    txtKitapID.setText(""); // ID'yi temizle
                    txtKitapAdi.setText(""); // Adı temizle
                }

            } else {
                // Kitap bulunamadı
                JOptionPane.showMessageDialog(this, "Belirtilen Kitap ID'ye sahip bir kitap bulunamadı!", "Kitap Bulunamadı", JOptionPane.ERROR_MESSAGE);
                txtKitapID.setText("");
                txtKitapAdi.setText("");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Veritabanı hatası: " + e.getMessage(), "Hata", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (rs != null) rs.close();
                if (ps != null) ps.close();
                if (conn != null) conn.close();
            } catch (SQLException e) {
                System.err.println("Kaynakları kapatırken hata: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnKitapAraActionPerformed

    private void txtKitapAdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKitapAdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKitapAdiActionPerformed

    private void txtOgrenciIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOgrenciIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOgrenciIDActionPerformed

    private void txtOgrenciAdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOgrenciAdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOgrenciAdiActionPerformed

    private void btnOduncVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOduncVerActionPerformed
        // 1. Gerekli tüm bilgileri al
        String kitapID_str = txtKitapID.getText();
        String ogrenciID_str = txtOgrenciID.getText();
        String kitapAdi = txtKitapAdi.getText();
        String ogrenciAdi = txtOgrenciAdi.getText();
        String oduncTarihi = txtOduncTarihi.getText();
        String iadeTarihi = txtIadeTarihi.getText().trim(); // Kullanıcı girdiği için .trim() önemli

        // 2. Kapsamlı Kontrol: Gerekli alanlar dolu mu?
        //    (Kitap Adı ve Öğrenci Adı kutuları sadece "Ara" butonları başarılıysa doluyordu,
        //     bu yüzden onları kontrol etmek en önemlisi)
        if (kitapAdi.isEmpty() || ogrenciAdi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lütfen geçerli bir Kitap ve Öğrenci seçmek için 'Ara' butonlarını kullanın!", "Eksik Bilgi", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (iadeTarihi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lütfen bir iade tarihi girin! (YYYY-AA-GG formatında)", "Eksik Bilgi", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Basit tarih formatı kontrolü (daha karmaşık kontrol yapılabilir ama bu genelde yeterli)
        if (!iadeTarihi.matches("\\d{4}-\\d{2}-\\d{2}")) {
            JOptionPane.showMessageDialog(this, "İade tarihi formatı geçersiz! Lütfen YYYY-AA-GG formatında girin.", "Format Hatası", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3. Veritabanı UPDATE işlemi
        Connection conn = null;
        PreparedStatement ps = null;
        // SQL: Kitabın durumunu, tarihlerini ve kimin aldığını güncelle
        String sql = "UPDATE kitaplar SET durum = ?, odunc_tarihi = ?, iade_tarihi = ?, odunc_alan_ogrenci_id = ? "
                   + "WHERE kitap_id = ? AND durum = 'Rafta'";

        try {
            conn = Baglanti.baglan();
            if (conn == null) {
                JOptionPane.showMessageDialog(this, "Veritabanı bağlantısı kurulamadı!", "Hata", JOptionPane.ERROR_MESSAGE);
                return;
            }

            ps = conn.prepareStatement(sql);
            ps.setString(1, "Ödünç Verildi");        // durum
            ps.setString(2, oduncTarihi);            // odunc_tarihi
            ps.setString(3, iadeTarihi);             // iade_tarihi
            ps.setInt(4, Integer.parseInt(ogrenciID_str)); // odunc_alan_ogrenci_id
            ps.setInt(5, Integer.parseInt(kitapID_str));   // kitap_id (WHERE şartı için)

            // 4. Sorguyu çalıştır
            int sonuc = ps.executeUpdate();

            if (sonuc > 0) {
                JOptionPane.showMessageDialog(this, "Kitap başarıyla " + ogrenciAdi + " adlı öğrenciye ödünç verildi!");

                // Tüm formu temizle
                txtKitapID.setText("");
                txtKitapAdi.setText("");
                txtOgrenciID.setText("");
                txtOgrenciAdi.setText("");
                txtIadeTarihi.setText("");
                // (Ödünç tarihini tekrar bugünün tarihiyle doldurmak için constructor'daki kodu buraya kopyalayabilirsin
                //  ama şimdilik temiz kalsın.)
                
            } else {
                // Bu durum, kitap ID'si doğru olsa bile 'Ara'ya bastıktan sonra
                // başka biri kitabı almışsa (veya durumu 'Rafta' değilse) oluşur.
                JOptionPane.showMessageDialog(this, "Kitap ödünç verilemedi. Kitabın durumunu kontrol edin (belki de 'Rafta' değil).", "İşlem Başarısız", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            // MySQL'den tarih formatı hatası (örn: 2023-02-30) gelirse yakalarız
            if (e.getMessage().contains("Incorrect date value")) {
                JOptionPane.showMessageDialog(this, "İade tarihi geçersiz! (Örn: 30 Şubat). Lütfen YYYY-AA-GG formatında geçerli bir tarih girin.", "Geçersiz Tarih", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Veritabanı hatası: " + e.getMessage(), "Hata", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            // ID'ler sayı değilse (Bu 'Ara' butonlarında zaten kontrol ediliyor ama güvenlik için burada da durmalı)
            JOptionPane.showMessageDialog(this, "ID'ler sayısal olmalıdır!", "Format Hatası", JOptionPane.ERROR_MESSAGE);
        } finally {
            // 5. Bağlantıları her zaman kapat!
            try {
                if (ps != null) ps.close();
                if (conn != null) conn.close();
            } catch (SQLException e) {
                System.err.println("Kaynakları kapatırken hata: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnOduncVerActionPerformed

    private void btnOgrenciAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOgrenciAraActionPerformed
        String ogrenciID_str = txtOgrenciID.getText().trim();

        if (ogrenciID_str.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lütfen bir Öğrenci ID girin!", "Uyarı", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int ogrenciID;
        try {
            ogrenciID = Integer.parseInt(ogrenciID_str);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Öğrenci ID bir sayı olmalıdır!", "Hata", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Connection conn = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String sql = "SELECT isim FROM ogrenciler WHERE ogrenci_id = ?";

        try {
            conn = Baglanti.baglan();
            if (conn == null) {
                JOptionPane.showMessageDialog(this, "Veritabanı bağlantısı kurulamadı!", "Hata", JOptionPane.ERROR_MESSAGE);
                return;
            }

            ps = conn.prepareStatement(sql);
            ps.setInt(1, ogrenciID);
            rs = ps.executeQuery();

            if (rs.next()) {
                String ogrenciAdi = rs.getString("isim");
                txtOgrenciAdi.setText(ogrenciAdi); // Öğrenci adını kutuya yaz
            } else {
                // Öğrenci bulunamadı
                JOptionPane.showMessageDialog(this, "Belirtilen Öğrenci ID'ye sahip bir öğrenci bulunamadı!", "Öğrenci Bulunamadı", JOptionPane.ERROR_MESSAGE);
                txtOgrenciID.setText("");
                txtOgrenciAdi.setText("");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Veritabanı hatası: " + e.getMessage(), "Hata", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (rs != null) rs.close();
                if (ps != null) ps.close();
                if (conn != null) conn.close();
            } catch (SQLException e) {
                System.err.println("Kaynakları kapatırken hata: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnOgrenciAraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new OduncVerFormu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKitapAra;
    private javax.swing.JButton btnOduncVer;
    private javax.swing.JButton btnOgrenciAra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txtIadeTarihi;
    private javax.swing.JTextField txtKitapAdi;
    private javax.swing.JTextField txtKitapID;
    private javax.swing.JTextField txtOduncTarihi;
    private javax.swing.JTextField txtOgrenciAdi;
    private javax.swing.JTextField txtOgrenciID;
    // End of variables declaration//GEN-END:variables
}
