/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import veritabani.Baglanti;

public class OgrenciKayitFormu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OgrenciKayitFormu.class.getName());

    /**
     * Creates new form OgrenciKayitFormu
     */
    public OgrenciKayitFormu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLable3 = new javax.swing.JLabel();
        jLable4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtogrenciID = new javax.swing.JTextField();
        txtIsim = new javax.swing.JTextField();
        txtBolum = new javax.swing.JTextField();
        txtSinif = new javax.swing.JTextField();
        btnKaydet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Öğrenci ID: ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("İsim: ");

        jLable3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLable3.setForeground(new java.awt.Color(204, 0, 0));
        jLable3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLable3.setText("Bölüm: ");

        jLable4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLable4.setForeground(new java.awt.Color(204, 0, 0));
        jLable4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLable4.setText("Sınıf: ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ÖĞRENCİ KAYIT");

        btnKaydet.setBackground(new java.awt.Color(204, 0, 0));
        btnKaydet.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKaydet.setForeground(new java.awt.Color(255, 255, 255));
        btnKaydet.setText("KAYDET");
        btnKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaydetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(btnKaydet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLable3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLable4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBolum, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSinif, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIsim, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtogrenciID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtogrenciID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIsim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLable3)
                    .addComponent(txtBolum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLable4)
                    .addComponent(txtSinif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnKaydet)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaydetActionPerformed
        // 1. Metin kutularından verileri al
    String ogrenciID_str = txtogrenciID.getText().trim();
    String isim = txtIsim.getText();
    String bolum = txtBolum.getText();
    String sinif = txtSinif.getText();

        // 2. Boş alan kontrolü
        if (ogrenciID_str.isEmpty() || isim.isEmpty() || bolum.isEmpty() || sinif.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tüm alanlar doldurulmalıdır!", "Hata", JOptionPane.WARNING_MESSAGE);
            return; // Metoddan çık
        }

        int ogrenciID;
        // 3. Veritabanına INT olarak kaydedeceğimiz ID'yi String'den INT'e çevir
        try {
            ogrenciID = Integer.parseInt(ogrenciID_str);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Öğrenci ID bir sayı olmalıdır!", "Hata", JOptionPane.ERROR_MESSAGE);
            return; // Metoddan çık
        }

        // 4. Veritabanı işlemleri
        Connection conn = null;
        PreparedStatement ps = null;
        String sql = "INSERT INTO ogrenciler (ogrenci_id, isim, bolum, sinif) VALUES (?, ?, ?, ?)";

        try {
            conn = Baglanti.baglan();
            if (conn == null) {
                JOptionPane.showMessageDialog(this, "Veritabanı bağlantı hatası!", "Hata", JOptionPane.ERROR_MESSAGE);
                return;
            }

            ps = conn.prepareStatement(sql);
            ps.setInt(1, ogrenciID); // 1. soru işaretine int ID'yi koy
            ps.setString(2, isim);   // 2. soru işaretine ismi koy
            ps.setString(3, bolum);  // 3. soru işaretine bölümü koy
            ps.setString(4, sinif);  // 4. soru işaretine sınıfı koy

            // 5. Sorguyu çalıştır
            int sonuc = ps.executeUpdate(); // INSERT, UPDATE, DELETE için executeUpdate() kullanılır

            if (sonuc > 0) {
                JOptionPane.showMessageDialog(this, "Öğrenci başarıyla kaydedildi!");
                
                // Kayıttan sonra kutuları temizle (İsteğe bağlı ama güzel olur)
                txtogrenciID.setText("");
                txtIsim.setText("");
                txtBolum.setText("");
                txtSinif.setText("");
            }

        } catch (SQLException e) {
            // SQL Hata Kodu 1062 = Benzersiz anahtar (PRIMARY KEY) ihlali
            if (e.getErrorCode() == 1062) {
                JOptionPane.showMessageDialog(this, "Bu Öğrenci ID zaten kayıtlı!", "Kayıt Hatası", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Veritabanı hatası: " + e.getMessage(), "Hata", JOptionPane.ERROR_MESSAGE);
            }
        } finally {
            // 6. Bağlantıları her zaman kapat!
            try {
                if (ps != null) ps.close();
                if (conn != null) conn.close();
            } catch (SQLException e) {
                System.err.println("Kaynakları kapatırken hata: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnKaydetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new OgrenciKayitFormu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKaydet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLable3;
    private javax.swing.JLabel jLable4;
    private javax.swing.JTextField txtBolum;
    private javax.swing.JTextField txtIsim;
    private javax.swing.JTextField txtSinif;
    private javax.swing.JTextField txtogrenciID;
    // End of variables declaration//GEN-END:variables
}
